config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: { registrations: 'employees/registrations' }
  devise_for :admins

  namespace :admin do
    resources :employees
  end

  resources :categories, only: [:show, :index]

  get '/profile' => 'dashboard#profile'
  get '/edit_profile' => 'dashboard#edit_profile'
  patch '/update_profile' => 'dashboard#update_profile'

  root to: 'dashboard#profile'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :authenticate_admin!

  def index
    
  end

  def show

  end

  def update

  end

  def create

  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::AdminController
  before_action :authenticate_admin!
  before_action :get_employee, only: [:show, :edit, :update]


  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      render @employee
    end
  end

  def edit
  end

  def show
  end

  def update
    if @employee.update(employee_params)
      render @employee
    end
  end

  protected
  
  def employee_params
    params.require(:employee).permit(:name, :position)
  end

  def get_employee
    @employee = Employee.find(params[:id])
  end
end

app/controllers/admin/employess_controller.rb
class Admin::EmployeesController < AdminController
  def index
    authenticate_admin!
    @employees = Employee.all
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < ::Devise::RegistrationsController
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ::Devise::SessionsController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_employee!
  before_action :get_category, only: [:show]

  def index
    @categories = Category.all
  end

  def show
  end

  protected

  def get_category
    @category = Category.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_employee!
  before_action :get_profile, only: [:profile, :edit_profile, :update_profile]

  def profile
    @employee = current_employee
  end

  def edit_profile
  end

  def update_profile
    @employee.update(profile_params)

    redirect_to profile_path
  end

  protected
  
  def get_profile
    @employee = current_employee
  end

  def profile_params
    params.require(:employee).permit(:email, :name, :position)
  end
end

app/controllers/employees/registrations_controller.rb
class Employees::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    edit_profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/employees/_employee.html.haml
%h1= employee.name

%h2= employee.position

= link_to 'Edit Employee', edit_admin_employee_path(id: employee.id)
= link_to 'Back to Employees', admin_employees_path

app/views/admin/employees/_form.html.haml
= form_for [:admin, @employee] do |f|
  = f.label :name
  = f.text_field :name

  = f.label :position
  = f.text_field :position

  = f.submit 'Save Employee'

app/views/admin/employees/edit.html.haml
%h1 Edit Employee
= render 'form'

app/views/admin/employees/index.html.haml
%h1 This is the Index Page of Employees

= render @employees

app/views/admin/employees/new.html.haml
%h1 New Employee
= render 'form'

app/views/admin/employees/show.html.haml
=render @employee

app/views/categories/_category.html.haml
%h1= category.name

app/views/categories/index.html.haml
= render @categories

app/views/categories/show.html.haml
= render @category

app/views/dashboard/_form.html.haml
= form_for @employee, url: update_profile_path do |f|
  = f.label :name
  = f.text_field :name

  = f.label :position
  = f.text_field :position

  = f.submit 'Save Profile'

=link_to 'Back to your profile', profile_path

app/views/dashboard/edit_profile.html.haml
%h1 Edit Profile
= render 'form'

app/views/dashboard/profile.html.haml
%h1= @employee.name
%h2= @employee.position

=link_to 'Edit you profile', edit_profile_path

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>